Update README.md
cashubtc/nuts pull request #118
Opened 2024-05-10 10:05 UTC by minibits-cash

Add minibits into the wallet list

2024-05-10 10:07 UTC, thesimplekid approved these changes

2024-05-10 10:09 UTC, thesimplekid requested changes
This just adds it to the links not the actual wallet list so it wont be seen when the the markdown is rendered

2024-08-20 14:40 UTC, prusnak commented
superseded by https://github.com/cashubtc/nuts/pull/154

2024-08-29 19:34 UTC, prusnak commented
This can be closed since https://github.com/cashubtc/nuts/pull/154 has been merged

2024-08-29 19:41 UTC, closed without merging