BREAKING: NUT-04: `payment_hash` -> `hash`
cashubtc/nuts pull request #14
Opened 2023-04-27 08:18 UTC by callebtc

Critical update. We need to fix NUT-04 to not use the bolt11 `payment_hash` as this enables a third party to steal tokens from a user if they publicly post a Cashu invoice online or leak it in any other way. An attacker could compute the `payment_hash` and start hitting the mint with `POST /mint` requests until the invoice is paid. If the attacker is faster than the user, they get the ecash.

### What do we need to change?

**Wallets:**
- Very easy: simply rename the URL param from `payment_hash` to `hash` in `POST /mint`. You received the `hash` in the previous step when you called `GET /mint`. 
- This is simply for semantic consistency (as we're not using a payment hash anymore). An option would be to make mints backwards compatible for a transition period and accept both parameters.

**Mints:**
- Medium easy: instead of returning the payment hash in `NUT-03: GET /mint`, generate a random **urlsafe** string to look up the invoice state later in `POST /mint`. This either has to be stored in a database (so it can be mapped back to the invoice) _or_ it could be encrypted with the private key of the mint (which would make it stateless). 
- Any comments on these approaches are appreciated, especially from mint devs.
- **Edit:** It seems the easiest way to implement this in a mint would be to encrypt the `payment_hash` with the mint's private key (or: the hash of the private key string). Then pass that encrypted (random-looking) string we call `hash` to the user upon `GET /mint`. When the user then asks for `POST /mint`, the mint takes `hash`, decrypts it with the private key and gets `payment_hash` that can be used to look up the invoice state in the Lightning backend.

### Tracking progress of NUT-04 update (please report):

- [x] Nutshell (Status: ✅ [PR](https://github.com/cashubtc/cashu/pull/191))
- [x] [LNbits](https://github.com/lnbits/cashu) (Status: ✅ [PR](https://github.com/lnbits/cashu/pull/23))
- [x] [Feni](https://github.com/cashubtc/cashu-feni) (Status: ✅ [PR](https://github.com/cashubtc/cashu-feni/pull/47))
- [x] [Cashu.me](https://github.com/cashubtc/cashu.me) (Status: ✅ [PR](https://github.com/cashubtc/cashu.me/pull/40))
- [x] [Nutstash](https://github.com/gandlafbtc/nutstash-wallet) (Status: ✅ [PR](https://github.com/cashubtc/cashu-ts/pull/60))
- [ ] [Peanut](https://github.com/cashubtc/peanut)
- [x] [cashu-ts](https://github.com/cashubtc/cashu-ts) (Status: ✅ [PR](https://github.com/cashubtc/cashu-ts/pull/60))
- [x] [ngutech21/cashu-rs](https://github.com/ngutech21/cashu-rs) (Status: ✅ [commit](https://github.com/ngutech21/cashu-rs/commit/9e4020ff77fc99d32f39d659cf77b8c7191ca938))
- [x] [clarkmoody/cashu-rs](https://github.com/clarkmoody/cashu-rs) (Status: ✅ [commit](https://github.com/clarkmoody/cashu-rs/commit/64102eafa0a41a69a57920803b0dab9d14327cce))
- [x] [cashu-crab](https://github.com/thesimplekid/cashu-crab) (Status: ✅ [commit](https://github.com/thesimplekid/cashu-crab/commit/d138135613475af563191b113c82c77d539f1213))

Ping: @Egge7 @BilligsterUser @gandlafbtc @clarkmoody @ngutech21 @gohumble @thesimplekid

2023-04-27 08:35 UTC, BilligsterUser requested changes
LGTM

2023-04-27 08:35 UTC, BilligsterUser commented on 04.md
> +For that, a wallet sends a `POST /mint?payment_hash=<hash>` request with a JSON body to the mint. The body **MUST** include `BlindedMessages` (see [NUT-00][00]) that are worth a maximum of `<amount_s
`POST /mint?payment_hash=<hash>`-
`POST /mint?hash=<hash>`

2023-04-27 08:57 UTC, BilligsterUser approved these changes

2023-04-28 04:25 UTC, clarkmoody approved these changes
ACK

Fixed in https://github.com/clarkmoody/cashu-rs/commit/64102eafa0a41a69a57920803b0dab9d14327cce

2023-04-28 13:29 UTC, gandlafbtc commented
LGTM

2023-04-28 13:29 UTC, gandlafbtc approved these changes

2023-04-30 08:56 UTC, ngutech21 commented
Fixed in https://github.com/ngutech21/cashu-rs/commit/9e4020ff77fc99d32f39d659cf77b8c7191ca938

2023-05-04 00:12 UTC, thesimplekid commented
Fixed in https://github.com/thesimplekid/cashu-crab/commit/d138135613475af563191b113c82c77d539f1213

2023-05-04 03:18 UTC, gandlafbtc commented
https://github.com/cashubtc/cashu-ts/releases/tag/v0.7.2

2023-05-12 15:18 UTC, clarkmoody commented
> @gohumble @ngutech21 @clarkmoody please confirm that the `hash` you're producing is urlsafe (since we're using it in a URL param)! 🙏

Yes, I'm encoding as hex.

2023-06-03 12:18 UTC, callebtc commented
Thank you everyone for a smooth coordinated upgrade like the Solana people.

2023-06-03 12:18 UTC, merged