SIG_ALL: sign aggregated message all inputs and ouptuts
cashubtc/nuts pull request #149
Opened 2024-07-13 13:00 UTC by callebtc

2025-04-15 19:20 UTC, gudnuf approved these changes

2025-04-15 19:20 UTC, gudnuf commented on 11.md
> +If any one input has the signature flag `SIG_ALL`, then all of them are required to have the flag `SIG_ALL` and same `Secret.data` and `Secret.tags` (see [here](#sig_inputs)), otherwise an error is r
```suggestion
If any one input has the signature flag `SIG_ALL`, then all inputs are required to have the flag `SIG_ALL` and the same `Secret.data` and `Secret.tags` (see [here](#sig_inputs)), otherwise an error is returned.
```

2025-04-15 21:43 UTC, robwoodgate commented on 11.md
> +If the tag `n_sigs` is a positive integer, the mint will require `n_sigs` signatures from public keys specified in the `pubkeys` tag additional to the public key in `Secret.data`. If the number of va
Probably should spell out that each public key can sign only once. Schnorr sigs are non-deterministic, so same pubkey could provide two different signatures.

If the tag `n_sigs` is a positive integer, the mint will require a total of `n_sigs` verified signatures. The mint will verify signatures against each unique public key in the array of unique strings. `[data, ...pubkeys]`, comprising the `Secret.data` field and each of the public keys specified in the `pubkeys` tag. 

Only one verified signature from each public key will be counted. If the number of valid signatures is greater or equal to the number specified in `n_sigs`, the transaction is valid. The individual signatures are provided in an array of strings in the `P2PKWitness` object.

2025-04-16 09:09 UTC, robwoodgate commented on 11.md
> +If the tag `n_sigs` is a positive integer, the mint will require `n_sigs` signatures from public keys specified in the `pubkeys` tag additional to the public key in `Secret.data`. If the number of va
The other thing which was unclear in original spec is what happens if n_sigs is omitted.

Should n_sigs =1 be considered the default (as SIG_INPUTS is) or does it mean the mint will disregard any pubkeys in the pubkeys tag and only allow the pubkey in Secret.data to sign?

2025-04-16 13:44 UTC, robwoodgate reviewed
While this NUT is under review, it might be a good idea to codify the maximum secret length as many mints are enforcing 512 bytes

2025-04-18 04:51 UTC, callebtc commented
> While this NUT is under review, it might be a good idea to codify the maximum secret length as many mints are enforcing 512 bytes

I think we should do that in NUT-0

2025-04-18 06:49 UTC, robwoodgate approved these changes

2025-04-18 08:43 UTC, callebtc commented
> This PR specifies the signature flag `SIG_ALL` for swap and for melt transactions involving P2PK-locked or HTLC-locked inputs. It also adds a new tag for P2PK (also used in HTLC) called `n_sigs_refund` that specifies the signature threshold for the `refund` pubkeys (enforced after a timelock).
> 
> `SIG_ALL` means that the witness of the _first input_ must be a signature on an concatenated message of the form `proof.secret_n.. . || output.B'_n...` in the case of a swap covering all of the inputs' `secret` fields and all of the outputs' blinded message fields `B_`. In the case of a melt, we also need to include the `quote_id` in the signed message.
> 
> Changes:
> 
> * fix SIG_ALL
> * add `n_sigs_refund`
> * removed `BlindedMessage.witness` 
> 
> Todo:
> 
> * [x]  specify if only valid for `/swap` or also for `/melt` (for both signature flags)
> * [ ]  `SIG_ALL` test vectors
> * [ ]  explicit error if no outputs are provided for `SIG_ALL`.

2025-04-22 17:55 UTC, robwoodgate commented on 11.md
> +If the tag `n_sigs` is a positive integer, the mint will require valid signatures from `n_sigs` public keys contained in the `Secret.data` field and the `pubkeys` tag.
If `n_sigs` is omitted, does the mint ignore the contents of the `pubkeys` tag?
Or will a default of `n_sigs` = 1 be assumed if `pubkeys` is present?

2025-04-23 09:34 UTC, robwoodgate requested changes
Have made some suggestions to clarify the multisig logic.
EDIT: Have PR'd these suggestions (#272)

2025-04-23 09:34 UTC, robwoodgate commented on 11.md
Sentence ends `The...`

**Suggestion:** 

If the `locktime` tag is in the past and the `refund` tag is present, the `Proof` is spendable only if a valid signature is given by at least ONE of the `refund` pubkeys.

If the `n_sigs_refund` tag is present and is a positive integer between `1` and `len(refund tag)`, the mint will require  at least`n_sigs_refund` pubkeys from the `refund` tag to provide valid signatures.

2025-04-23 09:34 UTC, robwoodgate commented on 11.md
> +If the tag `n_sigs` is a positive integer, the mint will require valid signatures from `n_sigs` public keys contained in the `Secret.data` field and the `pubkeys` tag.
**Suggestion:** 

If the `pubkeys` tag is present, the `Proof` is spendable only if a valid signature is given by at least ONE of the  public keys contained in the `Secret.data` field and the `pubkeys` tag.

If the `n_sigs` tag is present and is a positive integer between `1` and `len(pubkeys tag) + 1`, the mint will require  at least`n_sigs` of those public keys to provide valid signatures.

> [!NOTE]
> Multisig conditions only apply if the `locktime` tag is not present, or is in the future.

2025-04-23 09:34 UTC, robwoodgate commented on 11.md
> +This is an example `Secret` that locks a `Proof` with a Pay-to-Pubkey (P2PK) condition that requires 2-of-3 signatures from the public keys in the `data` field and the `pubkeys` tag. If the `timelock
Would be good to add a second `refund` public key to make it clear the tag supports multiple keys.

**Suggestion:**

... becomes spendable with a single signature from one of the two public keys in the `refund` tag.

2025-04-26 08:48 UTC, lollerfirst commented
NOTE: maybe it would be convenient to include a limit of `len(pubkeys) + len(refund) == NUT11_LIMIT`, since we already discussed it.

2025-05-16 15:06 UTC, thesimplekid commented
Closes #148

2025-06-29 12:31 UTC, thesimplekid commented
CDK PR: https://github.com/cashubtc/cdk/pull/862

2025-08-19 22:44 UTC, thesimplekid approved these changes

2025-08-19 22:48 UTC, merged