Add spec for binary token serialization
cashubtc/nuts pull request #199
Opened 2024-11-28 09:39 UTC by Egge21M

This adds some standardization for upcoming raw / binary token serialization, simply prepending the token with a identifier, as well as a version "byte" and encoding everything using `cbor`.

2024-11-28 09:57 UTC, prusnak commented
I am not a big fan of this proposal because it is not very flexible and requires cbor dependency for future versions which might not be based on cbor.

IMO much better encoding is just simple:

`CRAW <uint8_t version> <binary data>`

That way an app can very simply check whether it understands the payload by checking the first 5 bytes.

2024-11-28 10:00 UTC, Egge21M commented
> I am not a big fan of this proposal because it requires cbor dependency for future versions which might not be based on cbor.
> 
> IMO much better encoding is just simple:
> 
> `CRAW <uint8_t version> <binary data>`
> 
> That way an app can very simply check whether it understands the payload by checking the first 5 bytes.

Very good point, however this is meant to be for transports that are binary only. So we should probably do something like

`utf8(CRAW) <uint8_t version> <binary data>`

2024-11-29 10:29 UTC, prusnak requested changes

2024-11-29 10:29 UTC, prusnak commented on 00.md
> +- Token V4 Version: `utf8('CRAW') 0x02 cbor(token_object)`
```suggestion
- Token V3 Version: `utf8('CRAW') 0x03 <serialised_token>`
- Token V4 Version: `utf8('CRAW') 0x04 <serialised_token>`
```

2024-11-29 10:36 UTC, Egge21M commented on 00.md
> +- Token V4 Version: `utf8('CRAW') 0x02 cbor(token_object)`
Actually I would rather keep 1 & 2, as we use `A` & `B` for encoded token

2024-11-29 11:15 UTC, Egge21M commented on 00.md
> +- Token V4 Version: `utf8('CRAW') 0x02 cbor(token_object)`
Yeah, thats a good idea. So we will use the same version indicator as the regular tokens encoded as utf8 byte stream. I will also change the prefix to non-capitcal to be consistent with the regular encoding scheme.

2024-11-29 14:52 UTC, prusnak approved these changes
ACK

2024-12-12 13:54 UTC, callebtc commented on 00.md
> +utf8("craw") utf8(<token_version>) <serialised_token>
```suggestion
utf8("craw") | utf8(<token_version>) | <serialised_token>
```

where `|` denotes concatenation.

2024-12-12 13:59 UTC, callebtc commented on 00.md
> +- Token V4 Version: `utf8("craw") utf8("B") cbor(token_object)`
```suggestion
- Token V3 Version: `utf8("craw") || utf8("A") || cbor(token_object)`
- Token V4 Version: `utf8("craw") || utf8("B") || cbor(token_object)`
```

2024-12-12 14:00 UTC, callebtc approved these changes
LGTM

2024-12-12 14:00 UTC, merged