Draft: Well-known secret and P2PK
cashubtc/nuts pull request #40
Opened 2023-07-16 23:48 UTC by callebtc

2023-07-17 11:02 UTC, KKA11010 requested changes
This is well explained and it looks good to me. For now, I can't think of any blocker while implementing this into a wallet. 

All I found was just a tiny spelling error but I think you will get more valuable feedback from the other reviews:)

2023-07-18 20:05 UTC, thunderbiscuit reviewed
Approach ACK.

I'm not comfortable enough with my understanding of the signature scheme to give a full ACK or not, but the idea of placing conditions on the tokens is very interesting. I left a few comments for you if you want to tighten up the typos, as well as a question on the "anyone can spend" condition.

2023-07-18 20:05 UTC, thunderbiscuit commented on 10.md
> +If the tag `locktime` is the unix time and the mint's local clock is greater than `locktime`, the `Proof` becomes spendable by anyone, except if the following condition is also true.
I'm unclear as to how the mechanics of how "spendable by anyone" works. Can you clarify? I don't need any signature anymore? Just the serialized secret which is what the mint signed maybe? Not sure I understand yet.

2023-07-18 20:05 UTC, thunderbiscuit commented on 10.md
> +[20]: 20.md
As mentioned in #26, I'm not clear on why these are needed at the bottom, since it's unknown yet how many NUTs there will be in total and you only need a few links for each page. In this case the ones required are 00, 05, and 06.

2023-07-24 11:17 UTC, callebtc commented on 10.md
> +An ordinary ecash token is a set of `Proofs` each with a random string `secret`. To spend such a token in a [split][06] or a [melt][05] operation, wallets include `proofs` in their request each with
In NUT-00, we defined `Proofs` as an array of `Proof`s :)

2023-07-24 11:21 UTC, callebtc commented on 10.md
> +An ordinary ecash token is a set of `Proofs` each with a random string `secret`. To spend such a token in a [split][06] or a [melt][05] operation, wallets include `proofs` in their request each with
I think you're right in that regard that the wallet can represent the secret as they wish (as bytes) internally but the JSON field for communication with the mint will need to be string.

2023-07-24 11:24 UTC, callebtc commented on 10.md
> +- `tags` hold additional data  commited to and can be used for feature extensions
Thank you. I meant "feature", e.g., parameters for different `kind`s of locks.

2023-07-24 11:27 UTC, callebtc commented on 10.md
> +  "secret": '["P2PK",{"nonce": "5d11913ee0f92fefdc82a6764fd2457a","data": "026562efcfadc8e86d44da6a8adf80633d974302e62c850774db1fb36ff4cc7198",}]',
I think it shouldn't matter as long as it fits the `BlindMessage` and `BlindSignature`.

2023-07-24 11:28 UTC, callebtc commented on 10.md
> +**Note:** The tag serialization type is `[<str>, <str>]` but some tag values are `int`. Wallets and mints must cast types appropriately for de/serialization.
Should we just call it `int` and leave it up to the implementation? I think it's self-explanatory that the timestamp is unsigned.

2023-07-24 11:29 UTC, callebtc commented on 10.md
> +- `kind` is the kind of the spending condition, currently: `P2PK` or `P2SH`
I've lent the name `kind` from the nostr protocol, because this object very much looks like a nostr event.

2023-07-24 11:35 UTC, callebtc commented on 10.md
> +If the tag `n_sigs` is a positive integer, the mint will also consider signatures from public keys specified in one or more tags `pubkey` additional to the public key in `Secret.data`. If the number
Thank you.

2023-07-24 11:36 UTC, callebtc commented on 10.md
> +If the tag `locktime` is the unix time and the mint's local clock is greater than `locktime`, the `Proof` becomes spendable by anyone, except if the following condition is also true.
That's exactly right. "spendable by anyone" is how ecash transactions are handled right now in the default case. I will clarify this with an additional sentence.

2023-07-24 11:41 UTC, callebtc commented on 10.md
> +[20]: 20.md
I was just lazy and copy-pasted all links in all new documents :)

2023-08-01 20:35 UTC, supertestnet approved these changes

2023-08-01 20:35 UTC, supertestnet commented on 10.md
> +If the tag `locktime` is the unix time and the mint's local clock is greater than `locktime`, the `Proof` becomes spendable by anyone, except if the following condition is also true. Note: A `Proof`
you spelled default wrong on line 144 -- otherwise I have reviewed and approve it

2023-08-10 17:34 UTC, AngusP commented on 10.md
> +- `kind` is the kind of the spending condition, currently: `P2PK` or `P2SH`
> this object very much looks like a nostr event.

Is that itself perhaps a confusion that should be avoided? Given these aren't *actually* nostr compatible

2023-10-13 19:28 UTC, merged