The great cleanup wishlist
cashubtc/nuts pull request #55
Opened 2023-10-03 10:45 UTC by callebtc

This is a PR that encapsulates a collection of changes to the protocol that will make our lives easier in the future.

It includes: 
- New response to `GET /keys`
- New response to `GET /keysets`
- New method to calculate keyset id (without base64)

2023-10-03 10:56 UTC, dipunm commented on 01.md
> +      "symbol": <currency_symbol_str>,
👀

2023-10-03 10:59 UTC, dipunm commented on 02.md
> +A keyset ID is an identifier for a specific keyset. It can be derived by anyone who knows the set of public keys of a mint. The keyset ID is stored in each `Proof` and therefore in a [token][TokenV3]
This would imply that a single token can have proofs from multiple keysets.

Is there a use case for this? We could reduce the payload if we don't repeat the keyset id in a response.

While we're refactoring you know..... 😅

2023-10-03 19:40 UTC, thesimplekid commented on 00.md
> +This new token format introduces a new token prefix, a versioning flag, and a URI prefix for making tokens clickable on the web.
Since the old tokens are removed from the nut I think saying new is confusing.

2023-10-03 19:40 UTC, thesimplekid commented on 03.md
> +To request the minting of tokens, a wallet `Alice` sends a `GET /mint?amount=<amount>` request with the requested amount `<amount>` in satoshis. The mint `Bob` then responds with a Lightning invoice.
> with the requested amount `<amount>` in satoshis.

Since keyset is being changed to support multiple units will this request always be in satoshis?

2023-10-03 20:04 UTC, dipunm commented on 03.md
> +To request the minting of tokens, a wallet `Alice` sends a `GET /mint?amount=<amount>` request with the requested amount `<amount>` in satoshis. The mint `Bob` then responds with a Lightning invoice.
Being able to specify unit is interesting... it can allow denominations of millisats and maybe even (don't shoot me) bits.

2023-10-11 15:17 UTC, callebtc commented on 02.md
> +A keyset ID is an identifier for a specific keyset. It can be derived by anyone who knows the set of public keys of a mint. The keyset ID is stored in each `Proof` and therefore in a [token][TokenV3]
Yes, this is possible according to the TokenV3 encoding. Some wallets use this to export their entire balance from multiple mints with a single token. Not sure how useful that is, something we might deprecate for a next encoding version.

2023-10-11 15:31 UTC, callebtc commented on 03.md
> +To request the minting of tokens, a wallet `Alice` sends a `GET /mint?amount=<amount>` request with the requested amount `<amount>` in satoshis. The mint `Bob` then responds with a Lightning invoice.
> will this request always be in satoshis?

The new `GET /v1/mint` allows wallets to specify `amount` (example: `1234`), currency `symbol` (example: `USD`), and payment method `method` (example: `bolt11`) in the request body.

2023-10-12 04:34 UTC, thesimplekid commented on 03.md
> +To request the minting of tokens, a wallet `Alice` sends a `GET /mint?amount=<amount>` request with the requested amount `<amount>` in satoshis. The mint `Bob` then responds with a Lightning invoice.
> requested amount `<amount>` in satoshis.

In that case "in satoshis" should be removed I think.

2023-10-21 19:52 UTC, thunderbiscuit reviewed
A few overall comments: 
- The PR description states that the new v1 routes are to be used and the old ones are deprecated. Not sure how to handle that elegantly in the NUTs. Should examples for both be given? Or all examples be migrated to the v1? If so, most of those are not yet updated.
- Breaking changes means we should update the test vectors 
- How should tokens handle v1? Are there corner cases there that could create issues? What if you bundle a token with a ton of inputs, some v1 and some not? Haven't thought about this deeply, just writing down thoughts as they come to mind...

Overall some great improvements in there (also lots of new code to write for us! 😅). I suggest that if there is intention to eventually move forward with a solution to #54, it should be included here as part of this fairly wide-ranging set of breaking changes.

2023-10-21 19:52 UTC, thunderbiscuit commented on 01.md
This PR is called the great cleanup so I'll point this out: the files include links that are not valid, and I think that could be cleaned up here. My preference would be to add links at the bottom as needed in the document above instead of pre-emptively adding an arbitrary number (20) of them, for which many are non-existent NUTs.

2023-10-21 19:52 UTC, thunderbiscuit commented on 02.md
> +A keyset ID is an identifier for a specific keyset. It can be derived by anyone who knows the set of public keys of a mint. The keyset ID is stored in each `Proof` and therefore in a [token][TokenV3]
I agree that the "multiple mints per token" makes things more complicated than they could be, particularly because the use case for it is unclear. If you export your entire balance from multiple mints in a single token... at this point you're just exporting a data bundle; I think the word token looses its meaning and strength if it is too wide of a definition. Just my 2 cents. But like is stated above, this doesn't need to be solved here of course. Might just be something to think about for future refactorings.

2023-10-21 19:52 UTC, thunderbiscuit commented on 02.md
> +
I don't think the examples in other files are showcasing this version byte (they don't start with `00`). I think maybe adding a line as to why this version byte is useful might be good. Or you could just state it in the PR maybe so that we have a reference for later as per the thinking behind it.

2023-10-21 19:52 UTC, thunderbiscuit commented on 02.md
> +5 - prefix it with a keyset ID version byte
1. Are we hashing the string of numbers and letters or the byte array here? 
2. This reminds me that this PR should also udpate the test vectors for the small breaking changes like this one.

My preference would be to hash the concatenated bytes of all public keys. That way it's all bytes until the very end, where you pull the first 8 bytes of the hash and use their hex-encoded format.

2023-10-21 19:52 UTC, thunderbiscuit commented on 02.md
> +	return "00" + hashlib.sha256(pubkeys_concat.encode("utf-8")).hexdigest()[:14]
Should this be `.hexdigest()[:16]` instead?

2023-10-21 19:52 UTC, thunderbiscuit commented on 02.md
> +curl -X GET https://mint.host:3338/keys/9bb9d58392cd823e
Should these use the `v1/` paths? Wondering if communication with the mint using the old non-v1 paths are expected to stay with the base64 and only the v1 paths are expected to migrate to the new keyset ids.

2023-10-21 19:52 UTC, thunderbiscuit commented on 02.md
>  }
Because this is the response to the `keys/<keysetid>` GET request, I expected this response to not be an array of `"keysets"` since there can only be one (IIUC). Is there a reason for it to be that way? I'm thinking maybe this would work just as well:

```json
{
  "id": "9bb9d58392cd823e",
  "symbol": "sat",
  "keys": {
    "1": "03a40f20667ed53513075dc51e715ff2046cad64eb68960632269ba7f0210e38bc",
    "2": "03fd4ce5a16b65576145949e6f99f445f8249fee17c606b688b504a849cdc452de",
    "4": "02648eccfa4c026960966276fa5a4cae46ce0fd432211a4f449bf84f13aa5f8303",
    "8": "02fdfd6796bfeac490cbee12f778f867f0a2c68f6508d17c649759ea0dc3547528",
    ...
  }
}
```

2023-10-21 19:52 UTC, thunderbiscuit commented on 03.md
>  ## Example
I think it would be good to add an example of the v1 request body.

2023-10-21 19:52 UTC, thunderbiscuit commented on 03.md
> +with `method` being the payment method, `request` being the payment request and `id` is a **unique and random** id generated by the mint to internally look up the payment state. Note: `id` **MUST** r
Typo: ~stealing~ _steal_.

2023-10-21 19:52 UTC, thunderbiscuit commented on 03.md
> +Currently,
I think this part was forgotten. Did you mean to finish this or remove it?

2023-10-21 19:52 UTC, thunderbiscuit commented on 04.md
> +POST https://mint.host:3338/mint?id=67d1d9ea6ada225c115418671b64a
This might be a v1 path instead of the old one. Or does that change apply to the old requests as well?

2023-10-21 19:52 UTC, thunderbiscuit commented on 04.md
> +    "id": "9bb9d58392cd823e",
Again just a reminder that the keyset ids don't have the `00` prefix mentioned in NUT-02.

2023-10-27 16:06 UTC, thunderbiscuit commented
Great discussions over the dev call the other day. I figured I'd add a small todo list of things that might need to be addressed here before I forget. Note that not all of those might be required, and I'm going off of memory so hopefully not missing anything.

- [ ] Add note on standardized secrets (32 bytes of randomness), most likely transmitted as lowercase hex and why wallet should strive to follow the standard. Closes #54
- [ ] Make sure the `/info/` endpoint is future-proof and potentially adds messaging around breaking changes and supported features
- [ ] Consider the idea of using different endpoints for different units (additional NUTs for additional units would define new endpoints). If so, decide how to handle the default bolt11 `mint/` and `melt/` endpoints and their definition in the NUTs (are they good as is or do they now require their own spec file?)
- [ ] Add `unit` field to `Proof` object, requiring a new token format version (`cashuB`)
- [ ] Update all examples to the `v1` routes
- [ ] Address comments from reviewers above

2023-11-18 11:53 UTC, thesimplekid commented on 02.md
> +5 - prefix it with a keyset ID version byte
> My preference would be to hash the concatenated bytes of all public keys. That way it's all bytes until the very end, where you pull the first 8 bytes of the hash and use their hex-encoded format.

This is my preference as well but the example code below it looks like it is concatenating the string of hex encoded pubkey. 

> This reminds me that this PR should also udpate the test vectors for the small breaking changes like this one.

+1

2023-11-18 21:17 UTC, thesimplekid commented on 02.md
> +    return "00" + hashlib.sha256(pubkeys_concat).hexdigest()[:14]
@thunderbiscuit commented this previously but this it was removed when the change to bytes was pushed. Step 4 states to take the first 14 characters of the hex encoded hash but the example implementation seems to take the first 14.

2023-11-18 21:30 UTC, thesimplekid commented on 02.md
>  }
This is my understanding as well, and I would prefer this response unless there is a reason for the list.

2023-11-19 09:31 UTC, thesimplekid commented on 04.md
>  "proofs" :
Can't comment on the correct line as it wasn't changed in this PR, but on line 77 [NUT-0] should be [NUT-00}

2023-11-22 21:03 UTC, thesimplekid commented on 02.md
> +A mint can have multiple keysets at the same time but **MUST** have at least one `active` keyset (see [NUT-01][01]). Tokens from inactive keysets are still accepted but new tokens **MUST** be redeeme
Should a mint have only one active key set per unit?

2023-11-22 21:03 UTC, thesimplekid commented on 02.md
> +A mint can have multiple keysets at the same time but **MUST** have at least one `active` keyset (see [NUT-01][01]). Tokens from inactive keysets are still accepted but new tokens **MUST** be redeeme
Should a mint have only one active key set per unit?

2023-11-23 03:07 UTC, callebtc commented
I've completed most of the Todos! I would suggest deferring these remaining suggestions to later since the cleanup in this round focusses more on breaking changes in the API.
> * Make sure the `/info/` endpoint is future-proof and potentially adds messaging around breaking changes and supported features

I think these can be added as we go. What we should probably do already now is to indicate which (method, unit) pairs a mint supports.

> * [ ]  Add `unit` field to `Proof` object, requiring a new token format version (`cashuB`)

We can do it in cashuA and add a `unit` field in the JSON without breaking the format
> * [ ]  Potentially add errors enum with codes

I would love this but I'm afraid it needs to be in another PR


Thanks for the detailed comments and many errors you've found!

2023-11-23 07:15 UTC, thesimplekid commented on 05.md
>  The mint expects `Alice` to include `Proofs` of *at least* `total_amount = amount + fee_reserve` where `amount` is the amount to be paid with the Lightning invoice and `fee_reserve` is the maximum po
Is a call to the check fees endpoint still needed as the `fee_reserve` is included in the quote?

2023-11-23 07:15 UTC, thesimplekid commented on 08.md
>  NUT-08: Lightning fee return
I wonder if this should be made more general. I think most payment methods with fees will work in a similar way where the request is over paid and the change is returned as in cashu

2023-11-23 07:15 UTC, thesimplekid commented on 09.md
> +- `pubkey` is the hex pubkey of the mint.
How is this derived?

2023-11-23 15:52 UTC, moonsettler commented on 01.md
> +The mint responds only with his `active` keysets. Keyset are `active` if the mint will sign promises with. The mint will accept tokens from inactive keysets as inputs but will not sign with them for
yep. more than one just splits the anon set.

special case could be multiple currencies in the future (even with sidechains it's technically a floating exchange rate)

2023-11-23 16:01 UTC, moonsettler commented
One general observation in any context that is not obviously a keyset structure naming the keyset_id id is not intuitive at all.
ksid or keyset or keyset_id would probably be more appropriate. the other field names are pretty self explanatory except for the single letter stuff.

2023-11-26 18:54 UTC, thesimplekid commented on 00.md
>            "C": "02ac910bef28cbe5d7325415d5c263026f15f9b967a079ca9779ab6e5c2db133a7"
Think the example proofs here should be updated to the recommended 32 byte hex secret, even though that is not enforced.

2023-11-26 18:58 UTC, thesimplekid commented on 03.md
> +        "secret": "S+tDfc1Lfsrb06zaRdVTed6Izg",
Same comment as above, secret should be the recommended 32 byte hex

2023-11-29 13:43 UTC, ngutech21 commented
>Hexadecimal keyset IDs
...
> 4 - take the first 16 characters of the hex-encoded hash
The descriptions says to take the first 16 characters, but in the python implementation the first 14 characters are used.

2023-11-29 20:07 UTC, ngutech21 requested changes

2023-11-29 20:07 UTC, ngutech21 commented on 02.md
> +A keyset is a set of public keys that the mint `Bob` generates and shares with its users. It refers to the set of public keys that each correspond to the amount values that the mint supports (e.g. `1
Both endpoints /keys and /keysets are very similar. What was the general idea of having two endpoints that almost return the same data? Now /keys and /keysets both return `unit` and `id` and can therefore drift apart. In my opinion it would be easier to just have one endpoint that returns all key related data. If the client is only interested in active keysets, this could be accomplished by a query parameter. Having just one endpoint would be easier to maintain and result in less redundant code.

2023-11-29 20:07 UTC, ngutech21 commented on 03.md
> +The split operation is the most important component of the Cashu system. A split operation consists of multiple inputs (`Proofs`) and outputs (`BlindedMessages`). Mints verify and invalidate the inpu
I think the term split doesn't fit well anymore since we got rid of the amount field. This endpoint should be renamed to /swap, because it is less specific. Not every call to /split is indeed a split, but it transforms the inputs to outputs.

2023-11-29 21:06 UTC, thunderbiscuit reviewed
Tons of great work in here. I left some more comments. I see you have a few more todo items in your PR description so I don't want to approve it before you're actually done, but this is looking good IMO.

One thing I _think_ doesn't cause problem but I want to make sure I ask: are the v1 routes in any way impacting the way the tokens were before and are now built? As in, I don't _think_ mixing up proofs from old routes and proofs and new one from this newer cashu workflow can cause trouble inside a single cashu token, but can you confirm this to be true?

Lastly, I don't know where this might fit but there is a high-level mental model that took me a few weeks to really grasp I don't know why, and that was the key for me to not get lost in the sauce with all that new jargon/verbiage. Here is how I would write it (again don't know where it fits or if it's even needed, maybe just split into parts at the top of the split/melt/mint files?)

The Cashu protocol defines 3 types of interactions that can happen between a client and a mint, where the client can exchange:
1. ecash tokens for ecash tokens (called a **split** operation)
2. bitcoin for ecash tokens (called a **mint** operation)
3. ecash tokens for bitcoin (called a **melt** operation)

2023-12-01 07:31 UTC, ngutech21 commented on 05.md
> +The mint `Bob` then responds with a `PostMeltBolt11Response`:
How does the mint return overpaid fees? I think we should add an additional `change` field to the response like we did before the cleanup

2023-12-01 07:34 UTC, ngutech21 commented on 05.md
> +  "proof": <str>
The term proof is ambigous in this context, because it doesn't refer to a cashu Proof but a bolt11 payment preimage. `payment_preimage` might be a better name since this is a specific bolt11 response we can use the lightning terminology.

2023-12-01 07:34 UTC, ngutech21 commented on 05.md
> +`paid` is a boolean indicating whether the payment was successful, and `proof` being the bol11 payment preimage.
typo: bolt11 payment preimage

2023-12-04 22:33 UTC, thesimplekid commented on 11.md
> +This is an example `secret` that locks a `Proof` with a Pay-to-Pubkey (P2PK) condition that requires 2-of-3 signatures from the public keys in the `data` field amd the `pubkeys` tag. If the `timelock
> field amd

typo: and

2023-12-04 22:52 UTC, thesimplekid commented on 12.md
>  ```
Just to stay consistent `json`

2023-12-06 15:35 UTC, callebtc commented
All Todos are now closed and with that the PR is officially ready for review (and thanks for all reviews already 🙏)

Rocket emoji!

2023-12-07 14:27 UTC, thunderbiscuit approved these changes
ACK e59f284f0b786eb7b239715469f9e0dd9cd4b6ea. 

Major improvement of the protocol. I'm happy to see that we have a few implementations that were able to put this into code already, and looking forward to seeing what gets built on top of this. 🚀

2023-12-08 07:08 UTC, ngutech21 approved these changes
ACK e1568fdadc9e3e99d6a071e1de17a8a79dd658bf

This is a great improvement of the cashu protocol.

2023-12-08 21:18 UTC, thunderbiscuit commented on 00.md
> +  "id": hex_str
I was wrong, it does break in small ways the tests (not the validity of the tokens but their serialization).

For example note the example at the end of NUT-00 which has the order "id, amount, secret, C" (different from the model for `Proof` described above):
```json
"proofs": [
    {
        "id": "009a1f293253e41e",
        "amount": 2,
        "secret": "407915bc212be61a77e3e6d2aeb4c727980bda51cd06a6afc29e2861768a7837",
        "C": "02bc9097997d81afb2cc7346b5e4345a9346bd2a506eb7958598a72f0cf85163ea"
    },
    {
        "id": "009a1f293253e41e",
        "amount": 8,
        "secret": "fe15109314e61d7756b0f8ee0f23a624acaa3f4e042f61433c728c7057b931be",
        "C": "029e8e5050b890a7d6c0968db16bc1d5d5fa040ea1de284f6ec69d61299f671059"
    }
]
```

This means that a library that implemented the order described in the model section:
```json
{
  "amount": int, 
  "id": hex_str,
  "secret": str,
  "C": hex_str,
}
```

Will not be able to reproduce your resulting serialization in base64 (even though both tokens would be valid).

I suggest the order be "id, amount, secret, C" for both the model and the example.

2023-12-11 22:20 UTC, thesimplekid commented on 07.md
> +`Proofs` is a list (array) of `Proof`s (see [NUT-00][00]). `Alice` **CAN** provide a full `Proof` but **MUST** provide at least the `secret` (which is the only thing that `Bob` needs to check whether
Can this be used by the mint to finger print a wallet? If some wallets are checking by sending the full proof and others are only sending the secret? Should a recommendation be made to do one or the other similar to the ordering of the proofs to avoid fingerprinting?

2023-12-17 18:25 UTC, thesimplekid commented on 06.md
> +    "12": {"supported": true},
The trailing comma should be removed.

2023-12-18 21:47 UTC, merged