`/v1/check`: respond with array
cashubtc/nuts pull request #71
Opened 2023-12-31 13:13 UTC by callebtc

2023-12-31 19:53 UTC, thesimplekid commented
ACK [80750b2](https://github.com/cashubtc/nuts/pull/71/commits/80750b272433b2210bee64c067c3693ba4c3eddd)

2023-12-31 19:53 UTC, thesimplekid approved these changes

2024-01-03 19:29 UTC, thunderbiscuit requested changes
Small nit mentioned below.

I also approve of the idea of transforming `spendable` and `pending` into an enum as proposed by @callebtc, whether in this PR on another one.

2024-01-03 19:29 UTC, thunderbiscuit commented on 07.md
> +Where `secret` belongs to the provided `Proof` to check in the request, `spendable` and `pending` are booleans indicating whether is still spendable or pending, and `witness` is the witness data that
missing word(s): `indicating whether is still spendable or pending` -> `indicating whether the proof is still spendable or pending`

2024-01-05 14:53 UTC, callebtc commented on 07.md
> +Where `secret` belongs to the provided `Proof` to check in the request, `spendable` and `pending` are booleans indicating whether is still spendable or pending, and `witness` is the witness data that
Changed to enum instead of two lists!

2024-01-05 14:54 UTC, callebtc commented
@thesimplekid @thunderbiscuit I decided to rename the endpoint to `/v1/checkstate` instead of `/v1/check` because it expresses better what we are checking. Are you ok with that?

2024-01-05 17:39 UTC, thunderbiscuit approved these changes
ACK. 094b5b5f68f0d6a9b3cc71820f6d748a9de040f6.

2024-01-05 19:23 UTC, thesimplekid commented
ACK. https://github.com/cashubtc/nuts/commit/094b5b5f68f0d6a9b3cc71820f6d748a9de040f6. Rename is good with me

2024-01-06 11:01 UTC, merged