README Cleanup: Simplify mandatory table
cashubtc/nuts pull request #94
Opened 2024-03-08 10:15 UTC by AngusP

* For **mandatory** NUTS, just say `all` for wallet and mint support to reduce duplication
* Move the list of Wallets and Mints that support Mandatory NUTS to after the table, to make the full set of options clearer (also sort alpha)
* Markdown table formatting fixes, fix broken lnbits link
* mandatory NUT table can be human-readable

2024-03-08 10:15 UTC, AngusP commented on README.md
> +| [06][06] | Mint info                         | [Nutshell][py], [eNuts][enuts] | [Nutshell][py], [cashu-rs-mint][cashu-rs-mint] |
Left this row as it was given not all wallets+mints support it yet

2024-03-08 10:55 UTC, AngusP commented on README.md
> +| [12][12] | DLEQ proofs | [Nutshell][py] | [Nutshell][py] |
Just adds missing trailing `|`s

2024-03-19 09:53 UTC, callebtc requested changes
Chef's kiss! 

Could you move the wallet and mint list below all the tables so that both tables are side by side and not interrupted by a long list?

2024-03-19 13:49 UTC, thunderbiscuit commented
As is, it's a NACK for me. I think the information on which wallets and mints support which NUTs is important, but does not belong in the spec (see #81 for my full opinion on this). As the project grows and more and more mints and wallet libraries are created, tracking all of them and deciding whether they are up to date enough to be part of the table is a fool's errand IMO (example: Feni has not seen a commit in 6 months and is completely out of date with the spec).

But a simplification of the readme is a great idea. I like the break down into two table, one mandatory and one optional. The cleanest way to move forward IMO is simply with the following, simplified table format:

```md
| NUT #    | Description                       |
|----------|-----------------------------------|
| [00][00] | Cryptography and Models           |
| [01][01] | Mint public keys                  |
| [02][02] | Keysets and keyset IDs            |
| [03][03] | Swapping tokens                   |
| [04][04] | Minting tokens                    | 
| [05][05] | Melting tokens                    |
```

2024-03-21 16:59 UTC, thunderbiscuit commented
> That makes sense, though can be one of those things that we stop doing when it does become a faff to keep up-to-date. Early on, it's helpful to have as otherwise discovery can be hard.

Yeah I see your point. Discovery is very important (which is why I like the [awesome list](https://github.com/cashubtc/awesome-cashu), and [main website](https://docs.cashu.space/), and think we should use/promote them more). I do think we're past the early stages tough, and the way I see it, this page is now doing counter-discovery: there are a lot of cashu wallets/libraries/mints that are not in this list (and Feni which should be removed). If someone thinks of this list as some sort of canonical list coming from the devs of Cashu (what does that even mean? this repo is a spec!), they'll miss out on a lot. Again just my opinion, but this is I think creating more confusion and problems than it's worth, and will have to be removed no matter what at some point in the future. My opinion is, do it now.

2024-03-22 11:45 UTC, callebtc commented
Thank you this is much better! I agree, will remove Feni from the list, I think the dev is no contributing to GoNuts, which I added here.

2024-03-22 11:46 UTC, callebtc approved these changes

2024-03-22 11:46 UTC, merged